bitcoin/_posts/2018-06-10-bitcoin-s-energy-consumption.markdown, bitcoin/_posts/2018-08-17-the-magic-dust-of-cryptography.markdown, bitcoin/_posts/2018-12-21-philosophical-teachings-of-bitcoin.markdown, bitcoin/_posts/2019-01-11-economic-teachings-of-bitcoin.markdown, bitcoin/_posts/2019-04-02-technological-teachings-of-bitcoin.markdown
Mostly for consistency in citation style.
=> Fix small layout and linking issues in bitcoin articles

_includes/navigation.html, bitcoin/index.html, interviews.md
A little bit of audio never hurt anybody! 🎧
=> Add interviews section

_includes/lesson-list.html, _includes/lesson-navigation.html, _includes/lesson-toc.html, bitcoin/lessons/ch0-00-preface.md, bitcoin/lessons/ch0-01-introduction.md, bitcoin/lessons/ch1-00-philosophy.md, bitcoin/lessons/ch2-00-economics.md, bitcoin/lessons/ch3-00-technology.md
TODO: Introduction for chapters one and three.
=> [21 Lessons] Remove renaissance art from chapters [WIP]

bitcoin/lessons/ch1-01-immutability-and-change.md, bitcoin/lessons/ch1-02-the-scarcity-of-scarcity.md, bitcoin/lessons/ch1-03-an-immaculate-conception.md, bitcoin/lessons/ch1-04-the-problem-of-identity.md, bitcoin/lessons/ch1-05-replication-and-locality.md, bitcoin/lessons/ch1-06-the-power-of-free-speech.md, bitcoin/lessons/ch2-08-financial-ignorance.md, bitcoin/lessons/ch2-09-inflation.md, bitcoin/lessons/ch2-10-value.md, bitcoin/lessons/ch2-11-money.md, bitcoin/lessons/ch2-12-the-history-and-downfall-of-money.md, bitcoin/lessons/ch2-13-fractional-reserve-insanity.md, bitcoin/lessons/ch2-14-sound-money.md
=> Add links to dive deeper to Chapter 1 & 2

_config.yml, _includes/bibliography.md, _includes/sodes.html, bitcoin/resources.md, collections/_episodes/OTC25.md, collections/_episodes/POV22.md, collections/_episodes/SLP67.md, collections/_episodes/SLP71.md, collections/_episodes/SLP75.md, collections/_episodes/TFTC29.md, collections/_episodes/TFTC34.md, collections/_episodes/TFTC55.md, collections/_episodes/TFTC60.md, collections/_episodes/TFTC76.md, collections/_episodes/TIP244.md, collections/_episodes/WBD109.md, scripts/spreadsheet_to_resource_mds/spreadsheet_to_resource_mds.py
And some other minor improvements.
=> [Bitcoin Resources] Add support to scrape sodes from gdocs

bitcoin/resources-changelog.md, bitcoin/resources.md, collections/_books/grokking-bitcoin.md
See https://twitter.com/kallerosenbaum/status/1140596725759053824
=> [Bitcoin Resources] Add open-source version of Grokking Bitcoin

_includes/bibliography.md, bitcoin/resources.md
Add curations by Nick Ward, @igorbarinov, and @CypherPoet.
=> [Bitcoin Resources] Add curations by Nick Ward, igorbarinov, and cypherpoet

_includes/bibliography.md, bitcoin/resources-changelog.md, bitcoin/resources.md
=> [Bitcoin Resources] Add infominer curation and Unhashed podcast

bitcoin/lessons/ch3-21-metaphors-for-bitcoins-future.md
* Include non-public nodes in node count
* Add a link to [Luke Dashjr's node count page](https://luke.dashjr.org/programs/bitcoin/files/charts/software.html)
=> [21 Lessons] Fix node count in Lesson 21

bitcoin/lessons/ch3-16-reflections-on-dont-trust-verify.md
See https://github.com/bitcoin/bitcoin/pull/15277
=> [21 Lessons] Update guix section (guix PR was merged into bitcoin-core)

bitcoin/lessons/ch2-14-sound-money.md, collections/bitcoin/_posts/2019-01-11-economic-teachings-of-bitcoin.markdown
Thanks to JW for [pointing out](https://twitter.com/RunJdub/status/1154586469840957440) that mistake.
=> [21 Lessons] Fix begin date of reward era

collections/_episodes/OTC139.md, collections/_episodes/TFTC87.md
Added the following episodes:
* 🎧 Conner Brown on the intersubjective nature of Bitcoin - TFTC 87 hosted by Marty Bent
* 🎧 Saifedean Ammous on Austrian Economics and Bitcoin - OTC 139 hosted by Pomp
=> [Bitcoin-Resources] Add OTC 139 and TFTC 87

_includes/bibliography.md, bitcoin/resources-changelog.md, bitcoin/resources.md, collections/_episodes/C&G35.md, collections/_episodes/HF75.md, collections/_episodes/TIP252.md
- Add podcast: Hidden Forces by Demetri Kofinas
- Add podcast: Did You Know Crypto by Dustin D.
- Add article: Bitcoin Has No Intrinsic Value — and That’s Great by Conner Brown
- Add podcast episode: C&G #35 with Jameson Lopp
- Add podcast episode: TIP #252 with Trace Mayer
=> [Bitcoin Resources] Add Conner Brown's intrinsic value, HF 75, C&G 35, TIP252

_includes/bibliography.md, bitcoin/resources.md
=> [Bitcoin Resources] Remove Hidden Forces from podcast list

bitcoin/interviews.md
[It's alive!](https://anchor.fm/thecryptoconomy/episodes/CryptoChat_020---ITS-ALIVE---Brandon-Quittem--Der-Gigi-on-the-Bitcoin-Organism-e522gb)
=> [Interviews] Add interview with Guy Swann and Brandon Quittem

_layouts/post.html, collections/bitcoin/_posts/2018-08-17-the-magic-dust-of-cryptography.markdown, collections/bitcoin/_posts/2019-05-01-bitcoins-gravity.markdown, collections/bitcoin/_posts/2019-08-07-proof-of-life.markdown, collections/bitcoin/_posts/2019-08-22-the-rise-of-the-sovereign-individual.markdown
Thank you, Guy. 
* https://twitter.com/TheCryptoconomy/
* https://anchor.fm/TheCryptoconomy
* https://www.patreon.com/thecryptoconomy
* https://thecryptoconomy.com/
=> Add audio player to articles read by Guy Swann

collections/bitcoin/_posts/2019-12-22-bitcoin-s-eternal-struggle.markdown, collections/bitcoin/_posts/2020-03-01-bitcoin-s-habitats.markdown
Read by Guy Swan - thecryptoconomy.com
=> Add audio versions for Bitcoin's Habitats and Bitcoin's Eternal Struggle

collections/bitcoin/_posts/2020-04-27-dear-family-dear-friends.md
=> Add audio version of Dear Family, Dear Friends

collections/bitcoin/_posts/2019-05-01-bitcoins-gravity.markdown, collections/bitcoin/_posts/2020-07-21-true-names-not-required.md
=> [Translations] Add Italian translation of True Names and Gravity

scrape.sh
See [this SO answer](https://stackoverflow.com/a/4247319/11366019).
=> fix(script): fix scrape script for mac os

_layouts/post.html, collections/bitcoin/_posts/2018-06-10-bitcoin-s-energy-consumption.markdown, collections/bitcoin/_posts/2018-08-17-the-magic-dust-of-cryptography.markdown, collections/bitcoin/_posts/2018-12-21-philosophical-teachings-of-bitcoin.markdown, collections/bitcoin/_posts/2019-01-11-economic-teachings-of-bitcoin.markdown, collections/bitcoin/_posts/2019-04-02-technological-teachings-of-bitcoin.markdown, collections/bitcoin/_posts/2019-05-01-bitcoins-gravity.markdown, collections/bitcoin/_posts/2019-07-23-the-world-is-waking-up-to-bitcoin.markdown, collections/bitcoin/_posts/2019-08-07-proof-of-life.markdown, collections/bitcoin/_posts/2019-08-22-the-rise-of-the-sovereign-individual.markdown, collections/bitcoin/_posts/2019-10-03-how-to-kill-bitcoin.markdown, collections/bitcoin/_posts/2019-11-21-bitcoin-boots-on-the-ground-venezuela.markdown, collections/bitcoin/_posts/2019-12-22-bitcoin-s-eternal-struggle.markdown, collections/bitcoin/_posts/2020-03-01-bitcoin-s-habitats.markdown, collections/bitcoin/_posts/2020-03-20-dear-legacy-people.markdown, collections/bitcoin/_posts/2020-03-31-dear-bitcoiners.md, collections/bitcoin/_posts/2020-04-27-dear-family-dear-friends.md, collections/bitcoin/_posts/2020-06-15-the-bitcoin-journey.md, collections/bitcoin/_posts/2020-07-21-true-names-not-required.md, collections/bitcoin/_posts/2020-08-18-why-i-joined-swan-bitcoin.md, collections/bitcoin/_posts/2020-09-20-on-bitcoin-s-ux.md
Who needs years, months, and days, if we have blocktime?
=> feat: add blocktime support to bitcoin articles

_includes/navigation.html, bitcoin/index.html, collections/bitcoin/_posts/2019-05-01-bitcoins-gravity.markdown, collections/bitcoin/_posts/2019-08-07-proof-of-life.markdown, collections/bitcoin/_posts/2019-08-22-the-rise-of-the-sovereign-individual.markdown, collections/bitcoin/_posts/2020-03-31-dear-bitcoiners.md, collections/bitcoin/_posts/2020-04-27-dear-family-dear-friends.md, collections/bitcoin/_posts/2021-01-14-bitcoin-is-time.md, contact.md, index.html
* show selected articles on landing page
* show all articles under /bitcoin
* update about/contact page
=> feat: show selected articles on landing page

collections/bitcoin/_posts/2019-05-01-bitcoins-gravity.markdown
Fix markdown issue that produces double-quotes.
=> fix(gravity): double-quotes

canary.md, contact.md
Inspired by https://twitter.com/ZLOK/status/1234138061459591169?s=20
=> feat: add canary

collections/bitcoin/_posts/2021-06-13-bitcoin-is-an-idea.md
=> feat(idea): add audio

_config.yml, books/index.md, collections/_books/21-lessons.md, collections/_books/21-ways.md, contact.md, translations.md
=> feat(books): add /books

collections/bitcoin/_posts/2021-09-09-moving-towards-a-bitcoin-standard.md
=> feat: add omnipresence audio

collections/bitcoin/_posts/2018-06-10-bitcoin-s-energy-consumption.markdown, collections/bitcoin/_posts/2018-08-17-the-magic-dust-of-cryptography.markdown, collections/bitcoin/_posts/2019-05-01-bitcoins-gravity.markdown, collections/bitcoin/_posts/2019-07-23-the-world-is-waking-up-to-bitcoin.markdown, collections/bitcoin/_posts/2019-08-07-proof-of-life.markdown, collections/bitcoin/_posts/2019-08-22-the-rise-of-the-sovereign-individual.markdown, collections/bitcoin/_posts/2019-10-03-how-to-kill-bitcoin.markdown, collections/bitcoin/_posts/2019-11-21-bitcoin-boots-on-the-ground-venezuela.markdown, collections/bitcoin/_posts/2019-12-22-bitcoin-s-eternal-struggle.markdown, collections/bitcoin/_posts/2020-03-01-bitcoin-s-habitats.markdown, collections/bitcoin/_posts/2020-03-20-dear-legacy-people.markdown, collections/bitcoin/_posts/2020-03-31-dear-bitcoiners.md, collections/bitcoin/_posts/2020-04-27-dear-family-dear-friends.md, collections/bitcoin/_posts/2020-06-15-the-bitcoin-journey.md, collections/bitcoin/_posts/2020-07-21-true-names-not-required.md, collections/bitcoin/_posts/2020-08-18-why-i-joined-swan-bitcoin.md, collections/bitcoin/_posts/2020-09-20-on-bitcoin-s-ux.md, collections/bitcoin/_posts/2020-11-05-what-is-21ism.md, collections/bitcoin/_posts/2021-01-14-bitcoin-is-time.md, collections/bitcoin/_posts/2021-03-14-bitcoin-privacy-best-practices.md, collections/bitcoin/_posts/2021-03-14-the-responsibility-of-adopting-bitcoin.md, collections/bitcoin/_posts/2021-06-13-bitcoin-is-an-idea.md, collections/bitcoin/_posts/2021-08-02-implications-of-outlawing-bitcoin.md, collections/bitcoin/_posts/2021-09-09-moving-towards-a-bitcoin-standard.md
Will be as easy as [dergigi.com/time](https://dergigi.com/time) -- boom! :boom:
=> feat: add forwards for posts

media.md
https://humanb-film.com/en/home/
=> feat(media): add Human B

media.md
Also some text for the JBP interview.
=> feat(media): add EN/DE quick links

media.md
I am listening to this episode right now. The link was wrong aswell as the episode numer (38 instead of 30). Just made made a quick fix
=> fix: broken link

_includes/translations.html, collections/_threads/2019-10-30-circularity.md, collections/_threads/2021-03-13-pow-is-essential.md, collections/_threads/2021-08-10-memes-vs-the-world.md, collections/_threads/2021-12-12-why-shitcoins-are-a-waste-of-your-time.md, pow.md
- add translations
- add archive links
- various fixes
=> feat(threads): add shitcoin and meme thread

_includes/head.html
=> fix(lnurlp): always add suffix

collections/_episodes/20190419-kdc.md, collections/_episodes/20190421-kdc.md, collections/_episodes/20190508-ci.md, collections/_episodes/20190622-turm.md, collections/_episodes/20190623-kdc.md, collections/_episodes/20190624-turm.md, collections/_episodes/20190630-turm.md, collections/_episodes/20200120-kdc.md, collections/_episodes/20210215-euzz.md, collections/_episodes/20210410-dit.md, collections/_episodes/20210415-tt.md, collections/_episodes/20210801-b52.md, collections/_episodes/20210820-rdach.md, collections/_episodes/20211221-humanb.md, collections/_episodes/20220123-taverne.md, collections/_episodes/20220315-wbb.md, collections/_episodes/20220323-vdb.md, collections/_episodes/20220327-nodes.md, collections/_episodes/20220415-mises.md, scripts/spreadsheet_to_resource_mds/update_all.sh, scripts/spreadsheet_to_resource_mds/update_episodes.py
=> feat(media): scrape interviews from db

scripts/spreadsheet_to_resource_mds/update_episodes.py
=> fix(scripts): add guests

_includes/player.html, _layouts/post.html, collections/bitcoin/_posts/2022-09-10-cryptography-is-not-enough.md
=> feat: Cryptography is not enough

collections/bitcoin/_posts/2022-10-02-bitcoin-is-digital-scarcity.md
I picked up a couple others while I was going through it again
=> fix(digital): grammar and vocabulary

collections/bitcoin/_posts/2022-10-02-bitcoin-is-digital-scarcity.md
=> feat(digital): add audio

collections/_threads/2022-11-25-attention.md
https://twitter.com/dergigi/status/1596126980402864131
=> feat: add /attention

collections/bitcoin/_posts/2022-09-10-cryptography-is-not-enough.md
=> fix(cryptography): transcript

collections/bitcoin/_posts/2022-11-26-bitcoin-ist.md
h/t [Sinautoshi](https://twitter.com/Sinautoshi_8_21/status/1596577285712138240)
=> fix(momo): weird dash

_includes/article-list.html, bitcoin/index.html, blog/index.html, words.html
...for CTRL+F and other things.
=> feat(words): add list of article codes

license.md, support.md, value.md
Some rewording, some new links, some fixes.
=> feat(support): update /support and /value pages

contact.md
=> feat(contact): twitter -> nostr

_includes/post-cards.html, collections/bitcoin/_posts/2023-01-19-how-to-build-a-nostr-gm-bot.md, collections/bitcoin/_posts/2023-04-04-purple-text-orange-highlights.md, contact.md, nostr.md, nostr/index.html, words.html
[/nostr](https://dergigi.com/nostr)
=> feat: add /nostr

collections/bitcoin/_posts/2020-04-27-dear-family-dear-friends.md
Used w3.to Nostr url shortner
https://arabic.saifedean.com/%d9%85%d9%82%d8%a7%d9%84%d8%a7%d8%aa-%d9%85%d8%aa%d9%82%d8%af%d9%85%d8%a9/%d8%b1%d8%b3%d8%a7%d9%84%d8%a9-%d9%84%d9%83%d9%84-%d9%85%d9%86-%d9%84%d9%85-%d9%8a%d9%85%d8%aa%d9%84%d9%83-%d8%a7%d9%84%d8%a8%d9%8a%d8%aa%d9%83%d9%88%d9%8a%d9%86-%d8%a8%d8%b9%d8%af/
=> fix: updated Arabic translation link

bitcoin/index.html, code.md, contact.md
“They call it the drowning instinct. It's when drowning doesn't look like drowning.”
=> feat(contact): no DMs

projects.md
=> Re-word, remove outdated projects, fix markdown

support.md
...also updates LN Addr footnote.
=> feat(support): add others
